# ================================================================================
# BUILDER
# ================================================================================
name: builder
run-name: Build the project executable !
# --------------------------------------------------------------------------------
on: workflow_calls
# --------------------------------------------------------------------------------
jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
