# ================================================================================
# BUILDER
# ================================================================================
name: builder
run-name: Build the project executable !
# --------------------------------------------------------------------------------
on: workflow_calls
# --------------------------------------------------------------------------------
jobs:
  dep1:
    uses: ./.github/workflows/tests/tester.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  builder:
    runs-on: ubuntu-latest
    needs: [dep1] # Require the code to be tested

    steps:
      - name: Test
        run: |
          echo "I'm running building !"
