# ================================================================================
# DOCUMENTATION
# ================================================================================
name: doc
run-name: Build the documentation of the project, on an HTML and PDF (LaTeX) formats !
# --------------------------------------------------------------------------------
on: workflow_calls
# --------------------------------------------------------------------------------
jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
