# ===========================================================================================================
# docker/dockerfile
# 
# Handle the docker image configuration for the whole tool
#
# ===========================================================================================================

# Load the base ubuntu image:
FROM ubuntu:latest

# Set environment variables for non-interactive apt operations
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Update OS
RUN apt update && apt install -y

# Install build dependencies
RUN apt-get -y install \
    crossbuild-essential-arm64 \
    clang-format \
    cmake \ 
    make \
    git

RUN apt-get -y install \
    doxygen \
    graphviz

RUN apt-get -y install \
    python3 \
    python3-pip

# Set the working directory inside the container
WORKDIR /app

# Define a toolchain file for CMake (recommended for robust cross-compilation)
# This creates a file named 'toolchain.cmake' inside the container (and is going to be used for automated configuration of the compilers)
RUN mkdir -p /usr/local/share/cmake/
RUN echo "SET(CMAKE_SYSTEM_NAME Linux)" > /usr/local/share/cmake/toolchain.cmake && \
    echo "SET(CMAKE_SYSTEM_PROCESSOR aarch64)" >> /usr/local/share/cmake/toolchain.cmake && \
    echo "SET(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)" >> /usr/local/share/cmake/toolchain.cmake && \
    echo "SET(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)" >> /usr/local/share/cmake/toolchain.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)" >> /usr/local/share/cmake/toolchain.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)" >> /usr/local/share/cmake/toolchain.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)" >> /usr/local/share/cmake/toolchain.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> /usr/local/share/cmake/toolchain.cmake

# Make the entrypoint executable (file is copied INTO the docker)
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Entrypoint for interactive use and set a default arguments (we use the private )
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["__all"]