# ================================================================================
# BUILDER
# ================================================================================
name: builder
run-name: Build the project executable !
# --------------------------------------------------------------------------------
on:
  workflow_call:
# --------------------------------------------------------------------------------
jobs:
  job_test:
    uses: ./.github/workflows/tester.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  builder:
    runs-on: ubuntu-latest
    needs: [job_test] # Require the code to be tested

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Fetch the docker image and load it
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: builder
          path: ${{ runner.temp }}
      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/builder.tar
          docker image ls -a

      # Building the executable
      - name: Building executable
        run: |
          make all DOCKER_NAME=builder BUILD_RELEASE=build

      - name: Upload executable (aarch64)
        uses: actions/upload-artifact@v4
        with:
          name: WirelessSpeaker
          path: build/WirelessSpeaker

      # Adding logs to the summary
      - name: Logging
        run: |
          echo "### Build executable ! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Built and uploaded executable ! :white_check_mark:" >> $GITHUB_STEP_SUMMARY

      # Adding logs to the summary
      - name: Logging compiler infos
        run: |
          echo "### Compiler informations ! :rocket:" >> $GITHUB_STEP_SUMMARY
          make infos DOCKER_NAME=builder >> $GITHUB_STEP_SUMMARY

  documentation:
    runs-on: ubuntu-latest
    needs: [job_test] # Require the code to be tested (launched by builder)

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Fetch the docker image and load it
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: builder
          path: ${{ runner.temp }}
      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/builder.tar
          docker image ls -a

      # Building the documentation
      - name: Building zip
        run: |
          make pdf DOCKER_NAME=builder BUILD_DOC=doc

      # Creating zip of the html pages
      - name: Zipping HTML documentation
        run: |
          zip -r ${{ runner.temp }}/WirelessSpeaker-html.zip doc/html

      # Uploading artifacts
      - name: Upload documentation (pdf)
        uses: actions/upload-artifact@v4
        with:
          name: WirelessSpeaker-pdf
          path: doc/WirelessSpeaker.pdf

      # Uploading artifacts
      - name: Upload documentation (html)
        uses: actions/upload-artifact@v4
        with:
          name: WirelessSpeaker-html
          path: ${{ runner.temp }}/WirelessSpeaker-html.zip

      # Adding logs to the summary
      - name: Logging
        run: |
          echo "### Built documentation ! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Built and uploaded HTML and PDF documentation ! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
