name: C/C++ CI
on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]
    types: [opened, synchronize]

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install clang-format
    - name: Check code formatting
      run: find src/ -iname '*.h' -o -iname '*.cpp' -o -iname '*.c' -o -iname '*hpp' | xargs clang-format -i -style=file -dry-run -Werror . | grep -v 'clang-format:'

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install
      run: sudo sh scripts/install.sh
    - name: make
      run: make all
