# ================================================================================
# DOCUMENTATION
# ================================================================================
name: doc
run-name: Build the documentation of the project, on an HTML and PDF (LaTeX) formats !
# --------------------------------------------------------------------------------
on:
  workflow_call:
# --------------------------------------------------------------------------------
jobs:
  documentation:
    runs-on: ubuntu-latest
    needs: [job_test] # Require the code to be tested (launched by builder)

    steps:
      - name: Test
        run: |
          echo "I'm running documentation building !"
