# ================================================================================
# DOCUMENTATION
# ================================================================================
name: doc
run-name: Build the documentation of the project, on an HTML and PDF (LaTeX) formats !
# --------------------------------------------------------------------------------
on: workflow_calls
# --------------------------------------------------------------------------------
jobs:
  dep1:
    uses: ./.github/workflows/tester.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  documentation:
    runs-on: ubuntu-latest
    needs: [dep1] # Require the code to be tested

    steps:
      - name: Test
        run: |
          echo "I'm running documentation building !"
