# ================================================================================
# DOCKER
# ================================================================================
name: docker
run-name: Build the docker image that will be used in the next few builders !
# --------------------------------------------------------------------------------
on:
  workflow_call:
# --------------------------------------------------------------------------------
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "I'm running docker creation !"
