# ================================================================================
# MERGER
# ================================================================================
name: merger
run-name: Checking code quality for the PR...
# --------------------------------------------------------------------------------
on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: tests
# --------------------------------------------------------------------------------
jobs:
  job_build:
    uses: ./.github/workflows/builder.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  merger:
    runs-on: ubuntu-latest
    needs: [job_build] # Require the executable and the documentation to be built

    steps:
      # Adding logs to the summary
      - name: Logging 1
        run: |
          echo "### Results :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All tests sucessfulls, merge enabled ! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
