# ================================================================================
# MERGER
# ================================================================================
name: merger
run-name: Handle the check before merging into the dev branch
# --------------------------------------------------------------------------------
on:
  pull_request:
    branches: [dev, main]
    types: [opened, synchronize, reopened]
# --------------------------------------------------------------------------------
jobs:
  job_build:
    uses: ./.github/workflows/builder.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  merger:
    runs-on: ubuntu-latest
    needs: [job_build] # Require the executable and the documentation to be built

      steps:
        - name: Test
          run: |
            echo "I'm running release !"
