# ================================================================================
# FORMATTER (C/Cpp)
# ================================================================================
name: Python CI
run-name: Check that Python sources files are correctly formatted !
# --------------------------------------------------------------------------------
on:
  workflow_call:
# --------------------------------------------------------------------------------
jobs:
  python-formatter:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install dependencies
      - name: Install python black formatter
        run: |
          sudo apt-get update && sudo apt-get install black

      # Checking format...
      - name: Check code formatting
        id: black_formatter
        run: |
          black . --check --verbose
        continue-on-error: true

      - name: Check for errors now...
        if: ${{ steps.black_formatter.outputs.exit_code != '0' }}
        run: |
          echo "Formatting failed !"
          exit 1

      # Adding logs to the summary
      - name: Logging
        run: |
          echo "### Python Formatter :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Formatting of the python files passed ! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
