# ================================================================================
# RELEASER
# ================================================================================
name: releaser
run-name: Generate a release when push on the main branch !
# --------------------------------------------------------------------------------
on:
  push:
    branches:
      - main
# --------------------------------------------------------------------------------
jobs:
  job_build:
    uses: ./.github/workflows/builder.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  releaser:
    runs-on: ubuntu-latest
    needs: [job_build] # Require the executable and the documentation to be built

    steps:
      - name: Download specific artifacts (html zip)
        uses: actions/download-artifact@v4
        with:
          name: WirelessSpeaker-html
          path: ${{ runner.temp }}/artifacts/
          merge-multiple: true
      - name: Download specific artifacts (pdf)
        uses: actions/download-artifact@v4
        with:
          name: WirelessSpeaker-pdf
          path: ${{ runner.temp }}/artifacts/
          merge-multiple: true
      - name: Download specific artifacts (executable)
        uses: actions/download-artifact@v4
        with:
          name: WirelessSpeaker
          path: ${{ runner.temp }}/artifacts/
          merge-multiple: true

      # Get a new revision ID
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          tag_prefix: "v"
          tag_template: "yyyy.mm.i"

      # Create a release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          token: ${{secrets.GH_PAT}}

          files: |
            ${{ runner.temp }}/artifacts/*

          draft: false
          generate_release_notes: true

      # Adding logs to the summary
      - name: Logging 1
        run: |
          echo "### Results :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Built and released a new version ! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
