# ================================================================================
# RELEASER
# ================================================================================
name: releaser
run-name: Generate a release when push on the main branch !
# --------------------------------------------------------------------------------
on:
  push:
    branches: [main]
# --------------------------------------------------------------------------------
jobs:
  dep1:
    uses: ./.github/workflows/builds/builder.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  dep2:
    uses: ./.github/workflows/builds/doc.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  releaser:
    runs-on: ubuntu-latest
    needs: [dep1, dep2] # Require the executable and the documentation to be built

    steps:
      - name: Test
        run: |
          echo "I'm running merger !"
