# ================================================================================
# TESTER
# ================================================================================
name: tester
run-name: Perform unittests on the source code !
# --------------------------------------------------------------------------------
on:
  workflow_call:
# --------------------------------------------------------------------------------
jobs:
  dep1:
    uses: ./.github/workflows/docker.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  dep2:
    uses: ./.github/workflows/cpp.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  dep3:
    uses: ./.github/workflows/py.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  testing:
    runs-on: ubuntu-latest
    needs: [dep1, dep2, dep3] # Require the code to be formatted AND the docker image to be ready

    steps:
      - name: Test
        run: |
          echo "I'm running tests !"
