# ================================================================================
# TESTER
# ================================================================================
name: tester
run-name: Perform unittests on the source code !
# --------------------------------------------------------------------------------
on:
  workflow_call:
# --------------------------------------------------------------------------------
jobs:
  job_docker:
    uses: ./.github/workflows/docker.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  job_cpp:
    uses: ./.github/workflows/cpp.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  job_py:
    uses: ./.github/workflows/py.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  testing:
    runs-on: ubuntu-latest
    needs: [job_docker, job_cpp, job_py] # Require the code to be formatted AND the docker image to be ready

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Fetch the docker image and load it
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: builder
          path: ${{ runner.temp }}
      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/builder.tar
          docker image ls -a

      # Compiling tests
      - name: Building tester
        run: |
          make tester DOCKER_NAME=builder BUILD_DEBUG=build_tests

      # Adding logs to the summary
      - name: Logging 1
        run: |
          echo "### UnitTests :rocket:" >> $GITHUB_STEP_SUMMARY

      # Running tests
      - name: Running tests
        id: unittest_exec
        run: |
          ./build_tests/UnitsTests -c -v >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

      - name: Check for errors now...
        if: ${{ steps.unittest_exec.outputs.exit_code != '0' }}
        run: |
          echo "Unit tests failed !"
          exit 1

      # Adding logs to the summary
      - name: Logging
        run: |
          echo "Unit Tests :white_check_mark:" >> $GITHUB_STEP_SUMMARY
