# ================================================================================
# TESTER
# ================================================================================
name: tester
run-name: Perform unittests on the source code !
# --------------------------------------------------------------------------------
on: workflow_calls
# --------------------------------------------------------------------------------
jobs:
  dep1:
    uses: docker.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  dep2:
    uses: cpp.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  dep3:
    uses: py.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  testing:
    runs-on: ubuntu-latest
    needs: [dep1, dep2, dep3] # Require the code to be formatted AND the docker image to be ready

    steps:
      - name: Test
        run: |
          echo "I'm running tests !"
