# ================================================================================
# TESTER
# ================================================================================
name: tester
run-name: Perform unittests on the source code !
# --------------------------------------------------------------------------------
on:
  workflow_call:
# --------------------------------------------------------------------------------
jobs:
  job_docker:
    uses: ./.github/workflows/docker.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  job_cpp:
    uses: ./.github/workflows/cpp.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  job_py:
    uses: ./.github/workflows/py.yml
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  testing:
    runs-on: ubuntu-latest
    needs: [job_docker, job_cpp, job_py] # Require the code to be formatted AND the docker image to be ready

    steps:
      - name: Test
        run: |
          echo "I'm running tests !"
